name: "Test"
on:
  push:

jobs:
  test-windows:
    if: true
    name: Windows Test
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Windows GUT CLI
        run: |
          godot --headless --quit -e
          godot --headless -gexit --path . -s addons/gut/gut_cmdln.gd

  test-linux:
    if: true
    name: Linux Test
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Linux GUT CLI
        run: |
          godot --headless --quit -e
          godot --headless -gexit --path . -s addons/gut/gut_cmdln.gd
