name: "Test"
on:
  push:
env:
  GODOT_VERSION: 4.2.1

jobs:
  test-windows:
    if: true
    name: Windows Test
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Windows Build
        run: |
          godot --headless -s --path $PWD addons/gut/gut_cmdln.gd

  test-linux:
    if: true
    name: Linux Test
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Linux Build
        run: |
          godot --headless -s --path $PWD addons/gut/gut_cmdln.gd

